/**
 * Bicep generator — turn a resolved {@link AzurePlan} into a deterministic
 * `main.bicep` preview. This is a *preview artifact only*: azx never deploys it
 * in POC #1. The output is intentionally readable and review-friendly, using the
 * plan's logical ids as Bicep symbol names and honoring the dependency graph.
 */

import type { AzurePlan, AzureResource } from "./types.js";

/** Pinned API versions per ARM type (stable, review-friendly). Exported so the
 * browser ARM-JSON emitter (`arm-template.ts`) pins the exact same versions. */
export const API_VERSIONS: Record<string, string> = {
  "Microsoft.App/managedEnvironments": "2024-03-01",
  "Microsoft.App/containerApps": "2024-03-01",
  "Microsoft.App/jobs": "2024-03-01",
  "Microsoft.DBforPostgreSQL/flexibleServers": "2024-08-01",
  "Microsoft.DBforPostgreSQL/flexibleServers/databases": "2024-08-01",
  "Microsoft.DBforPostgreSQL/flexibleServers/configurations": "2024-08-01",
  "Microsoft.CognitiveServices/accounts": "2024-10-01",
  "Microsoft.CognitiveServices/accounts/deployments": "2024-10-01",
  "Microsoft.Search/searchServices": "2023-11-01",
  "Microsoft.Storage/storageAccounts": "2023-05-01",
  "Microsoft.Storage/storageAccounts/blobServices/containers": "2023-05-01",
};

/**
 * Pinned Azure OpenAI model versions — newest known GA release per family.
 *
 * Omitting the version makes Azure pick its own default, which can already be in
 * a "deprecating — blocked for new deployments" state and fail preflight with a
 * cryptic error. Emitting an explicit, pinned version keeps the preview
 * reproducible and gives the user a concrete value to review/override.
 *
 * KNOWN LIMITATION (offline tool): model lifecycle drifts on the live catalog,
 * so any static map eventually points at a deprecated version. azx faithfully
 * emits the *requested* model; it does not substitute a different family. If the
 * requested model has been retired in the target catalog, preflight will reject
 * it — that is an environment/product signal, not a codegen defect. Long-term
 * options: live catalog lookup, a maintained map, or omit-and-document.
 * Models not listed here fall back to the service default version.
 */
export const MODEL_VERSIONS: Record<string, string> = {
  "gpt-4o": "2024-11-20",
  "gpt-4o-mini": "2024-07-18",
  "gpt-4.1": "2025-04-14",
  "gpt-4.1-mini": "2025-04-14",
  "text-embedding-3-large": "1",
  "text-embedding-3-small": "1",
  "text-embedding-ada-002": "2",
};

export function generateBicep(plan: AzurePlan): string {
  const idToSymbol = new Map<string, string>();
  const idToName = new Map<string, string>();
  for (const r of plan.resources) {
    idToSymbol.set(r.id, symbolFor(r.id));
    idToName.set(r.id, r.name);
  }

  const out: string[] = [];
  out.push("// ---------------------------------------------------------------------------");
  out.push("// main.bicep — generated by azx (App Intent Service · POC #1, dry-run engine)");
  out.push("// DRY-RUN PREVIEW ONLY — review before deploying. azx made no Azure calls.");
  out.push(`// Resolved region: ${plan.region}`);
  if (plan.budget) {
    out.push(`// Estimated cost: ~$${plan.budget.estimatedMonthlyUsd}/mo ${plan.budget.currency}`);
  }
  out.push("// ---------------------------------------------------------------------------");
  out.push("");
  out.push("targetScope = 'resourceGroup'");
  out.push("");
  out.push(`@description('Azure region for all resources.')`);
  out.push(`param location string = '${plan.region}'`);
  out.push("");
  if (plan.resources.some((r) => r.type === "Microsoft.DBforPostgreSQL/flexibleServers")) {
    out.push(`@description('Administrator login for the PostgreSQL flexible server.')`);
    out.push(`param postgresAdminLogin string = 'pgadmin'`);
    out.push("");
    out.push(`@secure()`);
    out.push(`@description('Administrator password for the PostgreSQL flexible server. Provide at deploy time.')`);
    out.push(`param postgresAdminPassword string`);
    out.push("");
  }

  for (const r of plan.resources) {
    out.push(...emitResource(r, idToSymbol, idToName));
    out.push("");
  }

  // Handy outputs for the most common resources.
  const outputs = emitOutputs(plan.resources, idToSymbol);
  if (outputs.length) out.push(...outputs, "");

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

// ---------------------------------------------------------------------------
// Per-resource emission
// ---------------------------------------------------------------------------

function emitResource(
  r: AzureResource,
  idToSymbol: Map<string, string>,
  idToName: Map<string, string>,
): string[] {
  const symbol = idToSymbol.get(r.id)!;
  const api = API_VERSIONS[r.type] ?? "2024-01-01";
  const child = isChild(r.type);
  const name = child ? hierarchicalName(r, idToName) : r.name;

  const lines: string[] = [];
  for (const note of r.notes ?? []) lines.push(`// ${note}`);
  lines.push(`resource ${symbol} '${r.type}@${api}' = {`);
  lines.push(`  name: '${name}'`);
  if (!child) lines.push("  location: location");

  const kind = kindFor(r);
  if (kind) lines.push(`  kind: '${kind}'`);

  const sku = skuBlock(r);
  if (sku) lines.push(...indent(sku, 1));

  const props = propertiesBlock(r, idToSymbol);
  if (props) lines.push(...indent(props, 1));

  const deps = dependsOnBlock(r, idToSymbol);
  if (deps) lines.push(...indent(deps, 1));

  lines.push("}");
  return lines;
}

function skuBlock(r: AzureResource): string[] | undefined {
  switch (r.type) {
    case "Microsoft.DBforPostgreSQL/flexibleServers": {
      const sku = r.sku ?? "Standard_B1ms";
      const tier = sku.startsWith("Standard_B") ? "Burstable" : "GeneralPurpose";
      return ["sku: {", `  name: '${sku}'`, `  tier: '${tier}'`, "}"];
    }
    case "Microsoft.CognitiveServices/accounts":
      return ["sku: {", `  name: '${r.sku ?? "S0"}'`, "}"];
    case "Microsoft.Search/searchServices":
      return ["sku: {", `  name: '${r.sku ?? "basic"}'`, "}"];
    case "Microsoft.Storage/storageAccounts":
      return ["sku: {", `  name: '${r.sku ?? "Standard_LRS"}'`, "}"];
    case "Microsoft.CognitiveServices/accounts/deployments": {
      const capacity = numProp(r, "capacityK", 10);
      return ["sku: {", "  name: 'Standard'", `  capacity: ${capacity}`, "}"];
    }
    default:
      return undefined;
  }
}

function kindFor(r: AzureResource): string | undefined {
  if (r.type === "Microsoft.CognitiveServices/accounts") return "OpenAI";
  if (r.type === "Microsoft.Storage/storageAccounts") return "StorageV2";
  return undefined;
}

function propertiesBlock(r: AzureResource, idToSymbol: Map<string, string>): string[] | undefined {
  switch (r.type) {
    case "Microsoft.App/managedEnvironments":
      return ["properties: {}"];
    case "Microsoft.App/containerApps": {
      const port = numDeep(r, ["ingress", "targetPort"], 3000);
      const scale = (r.properties?.scale ?? {}) as { minReplicas?: number; maxReplicas?: number };
      const envSym = idToSymbol.get("app-env");
      return [
        "properties: {",
        ...(envSym ? [`  managedEnvironmentId: ${envSym}.id`] : []),
        "  configuration: {",
        "    ingress: {",
        "      external: true",
        `      targetPort: ${port}`,
        "    }",
        "  }",
        "  template: {",
          "    containers: [",
          "      {",
          "        name: 'app'",
          "        image: 'mcr.microsoft.com/k8se/quickstart:latest'",
          "        resources: {",
          "          cpu: json('0.5')",
          "          memory: '1.0Gi'",
          "        }",
          "      }",
          "    ]",
          "    scale: {",
          `      minReplicas: ${scale.minReplicas ?? 0}`,
        `      maxReplicas: ${scale.maxReplicas ?? 3}`,
        "    }",
        "  }",
        "}",
      ];
    }
    case "Microsoft.App/jobs": {
      const envSym = idToSymbol.get("app-env");
      return [
        "properties: {",
        ...(envSym ? [`  environmentId: ${envSym}.id`] : []),
        "  configuration: {",
        "    triggerType: 'Schedule'",
        "    replicaTimeout: 1800",
        "    scheduleTriggerConfig: {",
        "      cronExpression: '0 * * * *'",
        "    }",
        "  }",
        "  template: {",
        "    containers: [",
        "      {",
        "        name: 'job'",
        "        image: 'mcr.microsoft.com/k8se/quickstart-jobs:latest'",
        "        resources: {",
        "          cpu: json('0.5')",
        "          memory: '1.0Gi'",
        "        }",
        "      }",
        "    ]",
        "  }",
        "}",
      ];
    }
    case "Microsoft.DBforPostgreSQL/flexibleServers": {
      const storageGb = numProp(r, "storageGb", 32);
      const version = strProp(r, "version", "16");
      return [
        "properties: {",
        `    version: '${version}'`,
        "    administratorLogin: postgresAdminLogin",
        "    administratorLoginPassword: postgresAdminPassword",
        "    storage: {",
        `      storageSizeGB: ${storageGb}`,
        "    }",
        "    authConfig: {",
        "      passwordAuth: 'Enabled'",
        "    }",
        "}",
      ];
    }
    case "Microsoft.DBforPostgreSQL/flexibleServers/databases":
      return ["properties: {", "  charset: 'UTF8'", "  collation: 'en_US.utf8'", "}"];
    case "Microsoft.DBforPostgreSQL/flexibleServers/configurations": {
      const value = strProp(r, "value", "VECTOR");
      const source = strProp(r, "source", "user-override");
      return ["properties: {", `  value: '${value}'`, `  source: '${source}'`, "}"];
    }
    case "Microsoft.CognitiveServices/accounts":
      return [
        "properties: {",
        "  publicNetworkAccess: 'Enabled'",
        `  customSubDomainName: '${r.name}'`,
        "}",
      ];
    case "Microsoft.CognitiveServices/accounts/deployments": {
      const model = strProp(r, "model", "gpt-4o");
      const version = MODEL_VERSIONS[model];
      return [
        "properties: {",
        "  model: {",
        "    format: 'OpenAI'",
        `    name: '${model}'`,
        ...(version ? [`    version: '${version}'`] : []),
        "  }",
        "}",
      ];
    }
    case "Microsoft.Search/searchServices":
      return [
        "properties: {",
        "  replicaCount: 1",
        "  partitionCount: 1",
        "  hostingMode: 'default'",
        "}",
      ];
    case "Microsoft.Storage/storageAccounts":
      return [
        "properties: {",
        "  accessTier: 'Hot'",
        "  supportsHttpsTrafficOnly: true",
        "  minimumTlsVersion: 'TLS1_2'",
        "  allowBlobPublicAccess: false",
        "}",
      ];
    case "Microsoft.Storage/storageAccounts/blobServices/containers":
      return ["properties: {", "  publicAccess: 'None'", "}"];
    default:
      return undefined;
  }
}

function dependsOnBlock(r: AzureResource, idToSymbol: Map<string, string>): string[] | undefined {
  const deps = (r.dependsOn ?? []).map((id) => idToSymbol.get(id)).filter((s): s is string => Boolean(s));
  if (deps.length === 0) return undefined;
  return ["dependsOn: [", ...deps.map((s) => `  ${s}`), "]"];
}

function emitOutputs(resources: AzureResource[], idToSymbol: Map<string, string>): string[] {
  const lines: string[] = [];
  const web = resources.find((r) => r.id === "web");
  if (web) lines.push(`output webAppName string = ${idToSymbol.get("web")}.name`);
  const pg = resources.find((r) => r.id === "postgres");
  if (pg) lines.push(`output postgresServerName string = ${idToSymbol.get("postgres")}.name`);
  const st = resources.find((r) => r.id === "storage");
  if (st) lines.push(`output storageAccountName string = ${idToSymbol.get("storage")}.name`);
  return lines;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** True for ARM types nested under a parent (3+ path segments after provider). */
function isChild(type: string): boolean {
  const slashes = type.split("/").length; // provider + N segments
  return slashes >= 3;
}

/** Build the `parent/child` (or `parent/default/child`) name string for a child. */
function hierarchicalName(r: AzureResource, idToName: Map<string, string>): string {
  const parentId = r.dependsOn?.[0];
  const parentName = parentId ? idToName.get(parentId) : undefined;
  if (!parentName) return r.name;
  if (r.type.endsWith("blobServices/containers")) return `${parentName}/default/${r.name}`;
  return `${parentName}/${r.name}`;
}

/** Turn a logical id into a valid, unique Bicep symbol (camelCase). */
function symbolFor(id: string): string {
  const parts = id.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "res";
  const head = parts[0]!.toLowerCase();
  const rest = parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  const sym = [head, ...rest].join("");
  return /^[a-zA-Z]/.test(sym) ? sym : "r" + sym;
}

function indent(lines: string[], level: number): string[] {
  const pad = "  ".repeat(level);
  return lines.map((l) => (l.length ? pad + l : l));
}

function numProp(r: AzureResource, key: string, fallback: number): number {
  const v = r.properties?.[key];
  return typeof v === "number" ? v : fallback;
}

function strProp(r: AzureResource, key: string, fallback: string): string {
  const v = r.properties?.[key];
  return typeof v === "string" ? v : fallback;
}

function numDeep(r: AzureResource, path: string[], fallback: number): number {
  let cur: unknown = r.properties;
  for (const key of path) {
    if (cur && typeof cur === "object" && key in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[key];
    } else {
      return fallback;
    }
  }
  return typeof cur === "number" ? cur : fallback;
}
